### ISSUE TITLE
Serveur

### ISSUE THREAD

**Issue by developpeur-php** [Yovach/blablaland-protocol#1]
Salut, je voulais prendre contact avec toi concernant ce repo.
J'aimerais me lancer un petit defi et créer un petit serveur blablaland.
Je suis caler dev web mais tout ce qui est un peut plus bas niveau j'ai un peu de mal, possible de prendre contact sur discord pour pouvoir m'éclaircir en me donnant des liens de doc par exemple?
Me Gusta La Mañana#5384
Merci.

**Comment by Yovach** [comment]
Salut, je viens de voir ton Issue.
Il n'y a malheureusement pas de docs pour créer un serveur privé Blablaland. Il faut que tu décompile les fichiers clients (SWF) et que tu fasse l'algorithme serveur
